// Parses the human-edited review markdown (output/week-<id>.md) back into
// structured posts, so the orchestrator can diff it against the
// machine-generated baseline and log amendments per §6 of the architecture
// spec. Deliberately simple regex parsing — the file format is fixed and
// generated by build-review.js, not free-form prose.
const DAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

function parseReview(markdown) {
  const chunks = markdown.split(/\n---\n/);
  const posts = [];
  for (const chunk of chunks) {
    const dayMatch = chunk.match(/^## (\w+) — (.+)$/m);
    if (!dayMatch || !DAYS.includes(dayMatch[1])) continue;

    const hookMatch = chunk.match(/\*\*Hook:\*\* (.+)/);
    const copyMatch = chunk.match(/\*\*Copy:\*\*\n([\s\S]*?)\n\*\*CTA:\*\*/);
    const ctaMatch = chunk.match(/\*\*CTA:\*\* (.+)/);

    posts.push({
      day: dayMatch[1],
      pillar: dayMatch[2].trim(),
      hook: hookMatch ? hookMatch[1].trim() : '',
      copy: copyMatch ? copyMatch[1].trim() : '',
      cta: ctaMatch ? ctaMatch[1].trim() : '',
    });
  }
  return posts;
}

function diffPosts(baseline, edited) {
  const diffs = [];
  const fields = ['hook', 'copy', 'cta'];
  for (const basePost of baseline) {
    const editedPost = edited.find((p) => p.day === basePost.day);
    if (!editedPost) continue;
    for (const field of fields) {
      if (basePost[field] !== editedPost[field]) {
        diffs.push({ post: basePost.day, field, before: basePost[field], after: editedPost[field] });
      }
    }
  }
  return diffs;
}

module.exports = { parseReview, diffPosts, DAYS };
